#
# Github Action
#
# see https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action
# see https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions
# see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#

name: 'Checkout, Setup NodeJS + yarn and install dependencies'
description: 'Basic steps to setup a build with NodeJS and yarn'
runs:
    using: "composite"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          architecture: 'arm64'

      - name: Set up yarn
        run: npm i -g yarn && yarn --version
        shell: bash

      - name: Check NodeJS Options
        run: echo $NODE_OPTIONS && node -e 'console.log(`node heap limit = ${require("v8").getHeapStatistics().heap_size_limit / (1024 * 1024)} Mb`)'
        shell: bash

      - name: Install dependencies and build core packages
        run: yarn --prefer-offline --frozen-lockfile
        shell: bash
