#
# see https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action
# see https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions
# see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
name: 'Save app-env actions'
description: 'Set APP_ENV depending on the current branch'
inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: false
    default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
