#
# Github Workflow config file
#
# - reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# - composite actions: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
#

name: 'Base Node Setup'
runs:
    using: "composite"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          architecture: 'arm64'

      - name: Set up yarn
        run: npm i -g yarn && yarn --version

      - name: Check NodeJS Options
        run: echo $NODE_OPTIONS && node -e 'console.log(`node heap limit = ${require("v8").getHeapStatistics().heap_size_limit / (1024 * 1024)} Mb`)'

      - name: Install dependencies and build core packages
        run: yarn --prefer-offline --frozen-lockfile
