name: Cache Build

runs:
  using: "composite"
  steps:
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: 'json'
        filters: |
          packages:
            - 'packages/**'
    - name: Restore mtime for git checkout
      run: sudo apt install git-restore-mtime && sudo curl -o /usr/lib/git-core/git-restore-mtime https://raw.githubusercontent.com/MestreLion/git-tools/v2020.09/git-restore-mtime && git restore-mtime
    - name: Setup cache for dependencies
      uses: actions/cache@v2
      id: cache-node
      with:
        path: |
          node_modules
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-
    - name: Setup cache for build and dependencies
      uses: actions/cache@v2
      id: cache-lib
      with:
        path: |
          **/lib
          **/*.tsbuildinfo
        key: ${{ runner.os }}-${{ hashFiles('packages/*/src/**/*') }}
    - uses: dorny/paths-filter@v2
      id: filter2
      with:
        list-files: 'json'
        filters: |
          tsbuildinfo:
            - 'packages/**/*.tsbuildinfo'
    - name: Remove tsbuildinfo if files have changed
      uses: ./packages/core-github-actions/lib/remove-tsbuild-cache
      with:
        changed-files: ${{ steps.filter.outputs.packages_files }}
        tsBuildInfoFiles: ${{ steps.filter2.outputs.tsbuildinfo_files }}
