#
# reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# see: https://github.com/actions/cache/issues/459
#
name: build

on: [push]

jobs:
  #
  # Install dependencies with yarn, and save the node_modules
  #
  install-dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    #
    # BEGIN Cache node_modules, and ts build output
    #
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: 'json'
        filters: |
          packages:
            - 'packages/**'
    - name: Restore mtime for git checkout
      run: sudo apt install git-restore-mtime && sudo curl -o /usr/lib/git-core/git-restore-mtime https://raw.githubusercontent.com/MestreLion/git-tools/v2020.09/git-restore-mtime && git restore-mtime
    - name: Setup cache for build and dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          node_modules
          **/node_modules
          **/lib
          **/*.tsbuildinfo
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('packages/*/src/**/*') }}
    - uses: dorny/paths-filter@v2
      id: filter2
      with:
        list-files: 'json'
        filters: |
          tsbuildinfo:
            - 'packages/**/*.tsbuildinfo'
    - name: Remove tsbuildinfo if files have changed
      uses: ./packages/core-github-actions/lib/remove-tsbuild-cache
      with:
        changed-files: ${{ steps.filter.outputs.packages_files }}
        tsBuildInfoFiles: ${{ steps.filter2.outputs.tsbuildinfo_files }}
    #
    # END Cache node_modules, and ts build output
    #

    - name: Install dependencies
      run: yarn

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    #
    # BEGIN Cache node_modules, and ts build output
    #
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: 'json'
        filters: |
          packages:
            - 'packages/**'
    - name: Restore mtime for git checkout
      run: sudo apt install git-restore-mtime && sudo curl -o /usr/lib/git-core/git-restore-mtime https://raw.githubusercontent.com/MestreLion/git-tools/v2020.09/git-restore-mtime && git restore-mtime
    - name: Setup cache for build and dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          node_modules
          **/node_modules
          **/lib
          **/*.tsbuildinfo
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('packages/*/src/**/*') }}
    - uses: dorny/paths-filter@v2
      id: filter2
      with:
        list-files: 'json'
        filters: |
          tsbuildinfo:
            - 'packages/**/*.tsbuildinfo'
    - name: Remove tsbuildinfo if files have changed
      uses: ./packages/core-github-actions/lib/remove-tsbuild-cache
      with:
        changed-files: ${{ steps.filter.outputs.packages_files }}
        tsBuildInfoFiles: ${{ steps.filter2.outputs.tsbuildinfo_files }}
    #
    # END Cache node_modules, and ts build output
    #

    - name: Install dependencies
      run: yarn

    - name: Lint
      run: yarn lint

