name: build-and-deploy-to-netlify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    #
    # Cache yarn dependencies
    # https://github.com/actions/cache/blob/master/examples.md#node---yarn
    #
    - name: Yarn cache directory
      id: yarn-cache-dir
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Yarn cache
      uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    #
    # Fix for build issues with Gatsby or other tools that uses
    # many file watchers
    #
    - name: Increase system limit for number of file watchers
      run: |
        echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

    - name: Install dependencies
      run: yarn
      env:
        GRAPH_CMS_AUTH_TOKEN_MIR: ${{ secrets.GRAPH_CMS_AUTH_TOKEN_MIR }}
        GRAPH_CMS_API_URL_MIR: ${{ secrets.GRAPH_CMS_API_URL_MIR }}
        GRAPH_CMS_AUTH_TOKEN_NEWRADE: ${{ secrets.GRAPH_CMS_AUTH_TOKEN_NEWRADE }}
        GRAPH_CMS_API_URL_NEWRADE: ${{ secrets.GRAPH_CMS_API_URL_NEWRADE }}
    - name: Lint
      run: yarn lint

    - name: Build
      run: yarn build
      env:
        GRAPH_CMS_AUTH_TOKEN_MIR: ${{ secrets.GRAPH_CMS_AUTH_TOKEN_MIR }}
        GRAPH_CMS_API_URL_MIR: ${{ secrets.GRAPH_CMS_API_URL_MIR }}
        GRAPH_CMS_AUTH_TOKEN_NEWRADE: ${{ secrets.GRAPH_CMS_AUTH_TOKEN_NEWRADE }}
        GRAPH_CMS_API_URL_NEWRADE: ${{ secrets.GRAPH_CMS_API_URL_NEWRADE }}

    - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_NEWRADE }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true

    - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_MIR }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true

    - name: Test
      run: yarn test

      env:
        CI: true
