#
# Github Workflow config file
#
# - reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#

name: core

on:
  push:
    paths:
      - '.github/workflows/core-workflow.yml'
      - '**/package.json'
      - '**/package-lock.json'
      - '**/yarn.lock'
      - 'packages/core-*/**/*'
    branches:
      - dev
      - master
      - release
  pull_request:
  workflow_dispatch:

env:
  #
  # Debugging
  #
  DEBUG: 'newrade:*'
  #
  # Node
  #
  NODE_OPTIONS: '--max-old-space-size=4096'
  #
  # NVM
  #
  NVM_NODE_VERSION: ${{ secrets.NVM_NODE_VERSION }}
  #
  # Repo
  #
  MASTER_GIT_HOST: github.com
  MASTER_REPO_ORG: newrade
  MASTER_REPO_NAME: newrade-core
  PROJECT_GIT_HOST: github.com
  PROJECT_REPO_ORG: newrade
  PROJECT_REPO_NAME: newrade-core

jobs:

  build-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        all_but_latest: false
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false

    - name: Set up nvm
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        source ~/.profile
        nvm --version

    - name: Set up Node.js ${{ matrix.node-version }}
      run: |
        which node
        source ~/.profile
        nvm install v16
        nvm use v16
        node -v
        node -e 'console.log(process.arch)'

    - name: Set up yarn
      run: curl -o- -L https://yarnpkg.com/install.sh | bash && yarn --version

    - name: Check NodeJS Options
      run: echo $NODE_OPTIONS && node -e 'console.log(`node heap limit = ${require("v8").getHeapStatistics().heap_size_limit / (1024 * 1024)} Mb`)'

    - name: Clean
      run: yarn clean

    - name: Install dependencies and build core packages
      run: yarn --prefer-offline --frozen-lockfile

    - name: Lint Src Files
      run: yarn eslint ./packages/core-*/src/ --ext ts,tsx

    - name: Run unit tests
      run: yarn test --scope @newrade/core-*
