#
# Github Workflow config file
#
# - reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#

name: core

on:
  push:
    paths:
      - '.github/workflows/core-workflow.yml'
      - '**/package.json'
      - '**/package-lock.json'
      - '**/yarn.lock'
      - 'packages/core-*/**/*'
    branches:
      - dev
      - master
      - release
  pull_request:

env:
  #
  # Debugging
  #
  DEBUG: 'newrade:*'
  #
  # Node
  #
  NODE_OPTIONS: '--max-old-space-size=4096'
  #
  # NVM
  #
  NVM_NODE_VERSION: ${{ secrets.NVM_NODE_VERSION }}
  #
  # Repo
  #
  MASTER_GIT_HOST: ${{ secrets.MASTER_GIT_HOST }}
  MASTER_REPO_ORG: ${{ secrets.MASTER_REPO_ORG }}
  MASTER_REPO_NAME: ${{ secrets.MASTER_REPO_NAME }}
  PROJECT_GIT_HOST: ${{ secrets.PROJECT_GIT_HOST }}
  PROJECT_REPO_ORG: ${{ secrets.PROJECT_REPO_ORG }}
  PROJECT_REPO_NAME: ${{ secrets.PROJECT_REPO_NAME }}

jobs:

  build-test:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up yarn
      run: npm install --global yarn && yarn --version

    - name: Check NodeJS Options
      run: echo $NODE_OPTIONS && node -e 'console.log(`node heap limit = ${require("v8").getHeapStatistics().heap_size_limit / (1024 * 1024)} Mb`)'

    - name: Install dependencies and build core packages
      run: yarn --prefer-offline --frozen-lockfile

    - name: Lint Src Files
      run: yarn eslint ./packages/core-*/src/ --ext ts,tsx

    - name: Run unit tests
      run: yarn test --scope @newrade/core-*
