#
# Github Workflow config file
#
# - reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# - composite actions: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
#

name: core

on:
  push:
    paths:
      - '.github/actions/**/*'
      - '.github/workflows/core-workflow.yml'
      - '**/package.json'
      - '**/package-lock.json'
      - '**/yarn.lock'
      - 'packages/core-*/**/*'
    branches:
      - dev
      - master
      - release
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

env:
  #
  # Debugging
  #
  DEBUG: 'newrade:*'
  #
  # Node
  #
  NODE_OPTIONS: '--max-old-space-size=4096'
  #
  # NVM
  #
  NVM_NODE_VERSION: ${{ secrets.NVM_NODE_VERSION }}
  #
  # Repo
  #
  MASTER_GIT_HOST: github.com
  MASTER_REPO_ORG: newrade
  MASTER_REPO_NAME: newrade-core
  PROJECT_GIT_HOST: github.com
  PROJECT_REPO_ORG: newrade
  PROJECT_REPO_NAME: newrade-core

jobs:
  build-test:
    runs-on: self-hosted

    # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
    # Otherwise, clone it normally.
    if: |
        (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
        (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')

    steps:
      - name: 'Checkout, Setup NodeJS + yarn and install dependencies'
        uses: ./.github/actions/base-node-setup
