#
# Github Workflow config file
#
# - reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#

name: mir

on:
  push:
    paths:
      - '.github/workflows/mir-website-workflow.yml'
      - '**/package.json'
      - '**/package-lock.json'
      - '**/yarn.lock'
      - 'packages/core-*/**/*'
      - 'packages/mir-*/**/*'
    branches:
      - dev
      - master
      - release
  pull_request:

env:
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:

  build-test-deploy:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      if: github.event_name != 'pull_request'
      with:
        clean: false

    - name: Checkout (clean)
      uses: actions/checkout@v2
      if: github.event_name == 'pull_request'
      with:
        clean: true

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up yarn
      run: npm install --global yarn && yarn --version

    - name: Check NodeJS Options
      run: echo $NODE_OPTIONS && node -e 'console.log(`node heap limit = ${require("v8").getHeapStatistics().heap_size_limit / (1024 * 1024)} Mb`)'

    - name: Set the env variable depending on the branch
      uses: ./packages/core-github-actions/built/set-app-env

    - name: Install dependencies and build core packages
      run: yarn --prefer-offline

    - name: Clean
      run: yarn clean --scope @newrade/mir-website

    - name: Lint Src Files
      run: yarn eslint ./packages/mir-*/src/ --ext ts,tsx

    - name: Run unit tests
      run: yarn test --scope @newrade/mir-*

    - name: Build website
      run: yarn build --scope @newrade/mir-*
      env:
        NVM_NODE_VERSION: ${{ secrets.NVM_NODE_VERSION }}
        MASTER_GIT_HOST: ${{ secrets.MASTER_GIT_HOST }}
        MASTER_REPO_ORG: ${{ secrets.MASTER_REPO_ORG }}
        MASTER_REPO_NAME: ${{ secrets.MASTER_REPO_NAME }}
        PROJECT_GIT_HOST: ${{ secrets.PROJECT_GIT_HOST }}
        PROJECT_REPO_ORG: ${{ secrets.PROJECT_REPO_ORG }}
        PROJECT_REPO_NAME: ${{ secrets.PROJECT_REPO_NAME }}

        DEBUG: 'newrade:*'
        APP_URL: 'http://local.mirinc.ca'

        CONTENTFUL_ENV: ${{ secrets.CONTENTFUL_ENV }}
        CONTENTFUL_SPACEID_MIR: ${{ secrets.CONTENTFUL_SPACEID_MIR }}
        CONTENTFUL_DELIVERY_TOKEN_MIR: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN_MIR }}


