#
# reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# see: https://github.com/actions/cache/issues/459
#
name: build-self

on: [push]

jobs:

  install-dependencies:
    #
    # BEGIN COMMON
    #
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set the env variable depending on the branch
      uses: ./packages/core-github-actions/lib/set-app-env
    #
    # END COMMON
    #
    - name: Lint Src Files
      run: yarn lint

    - name: Install dependencies
      run: yarn
