#
# Github Workflow config file
#
# - reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#

name: vsb-api

on:
  push:
    paths:
      - '.github/workflows/vsb-api-workflow.yml'
      - '**/package.json'
      - '**/package-lock.json'
      - '**/yarn.lock'
      - 'packages/core-*/**/*'
      - 'packages/vsb-common/**/*'
      - 'packages/vsb-api/**/*'
    branches:
      - dev
      - master
      - release
  pull_request:
  workflow_dispatch:

env:
  #
  # Debugging
  #
  DEBUG: 'newrade:*'
  #
  # Node
  #
  NODE_OPTIONS: '--max-old-space-size=4096'
  #
  # NVM
  #
  NVM_NODE_VERSION: ${{ secrets.NVM_NODE_VERSION }}
  #
  # Repo
  #
  MASTER_GIT_HOST: ${{ secrets.MASTER_GIT_HOST }}
  MASTER_REPO_ORG: ${{ secrets.MASTER_REPO_ORG }}
  MASTER_REPO_NAME: ${{ secrets.MASTER_REPO_NAME }}
  PROJECT_GIT_HOST: ${{ secrets.PROJECT_GIT_HOST }}
  PROJECT_REPO_ORG: ${{ secrets.PROJECT_REPO_ORG }}
  PROJECT_REPO_NAME: ${{ secrets.PROJECT_REPO_NAME }}
  #
  # App
  #
  APP_DOMAIN: vasectomie-pierre-boucher.ca
  APP_SUBDOMAIN: api

  API_VSB_VENDOR_NAME: ${{ secrets.API_VSB_VENDOR_NAME }}
  API_VSB_VENDOR_EMAIL: ${{ secrets.API_VSB_VENDOR_EMAIL }}
  API_VSB_KEY_CLINIKO: ${{ secrets.API_VSB_KEY_CLINIKO }}
  API_VSB_SHARD_ID: ${{ secrets.API_VSB_SHARD_ID }}
  API_VSB_SECRET_KEY_RECAPTCHA: ${{ secrets.API_VSB_SECRET_KEY_RECAPTCHA }}

  API_VSB_STMP_USER: ${{ secrets.API_VSB_STMP_USER }}
  API_VSB_STMP_PASSWORD: ${{ secrets.API_VSB_STMP_PASSWORD }}

jobs:

  build-test-deploy:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        all_but_latest: true
        access_token: ${{ github.token }}

    - name: Inject Github slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up yarn
      run: npm install --global yarn && yarn --version

    - name: Check NodeJS Options
      run: echo $NODE_OPTIONS && node -e 'console.log(`node heap limit = ${require("v8").getHeapStatistics().heap_size_limit / (1024 * 1024)} Mb`)'

    - name: Set the env variable depending on the branch
      uses: ./packages/core-github-actions/built/set-app-env

    - name: Install dependencies and build core packages
      run: yarn --prefer-offline --frozen-lockfile

    - name: Clean
      run: yarn lerna:clean --scope @newrade/vsb-api

    - name: Lint Src Files
      run: yarn eslint ./packages/vsb-*/src/ --ext ts,tsx

    - name: Build vsb-common
      run: yarn lerna:build --scope @newrade/vsb-common

    - name: Run unit tests
      run: yarn lerna:test --scope @newrade/vsb-*
      env:
        NODE_ENV: test

    - name: Build
      run: yarn lerna:build --scope @newrade/vsb-api

    - name: Deploy
      if: ${{ env.APP_CI_DEPLOY }}
      uses: amondnet/vercel-action@v20
      with:
        scope: ${{ secrets.VERCEL_SCOPE }}
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-args: 'public'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
        vercel-project-id: prj_gdoOSnZGX67oP3i2oiuKePfTTMbi
        working-directory: ./packages/vsb-api
        alias-domains: |
          ${{ env.APP_HOST }}

    - name: Trigger Integration Workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: vsb-integration-workflow.yml
        token: ${{ secrets.PERSONAL_GH_TOKEN }}


