#
# Github Workflow config file
#
# - reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#

name: vsb-website-next

on:
  push:
    branches:
      - dev
      - master
      - release

jobs:

  build-test-deploy:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set the env variable depending on the branch
      uses: ./packages/core-github-actions/lib/set-app-env

    - name: Install dependencies and build core packages
      run: yarn --prefer-offline

    - name: Build vsb-website-next
      run: yarn build --scope @newrade/vsb-website-next

    - name: Check for protected branches
      if: endsWith(github.ref, 'api')
      run: echo "branch cannot end with 'api'" && exit 1

    - name: Deploy website (prod)
      if: (github.event_name == 'push')
      uses: amondnet/vercel-action@v20
      with:
        scope: ${{ secrets.VERCEL_SCOPE }}
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
        vercel-project-id: prj_ipqnwTyS8LUAFjgfGJr3m65KhWvQ
        working-directory: ./packages/vsb-website-next

