#
# Github Workflow config file
#
# - reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# - composite actions: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
#

name: ze-design-website

on:
  push:
    paths:
      - '.github/actions/**/*'
      - '.github/workflows/ze-design-website-workflow.yml'
      - '**/package.json'
      - '**/package-lock.json'
      - '**/yarn.lock'
      - 'packages/core-*/**/*'
      - 'packages/ze-*/**/*'
    branches:
      - dev
      - master
      - release
  pull_request:
  workflow_dispatch:

env:
  #
  # Debugging
  #
  DEBUG: 'newrade:*'
  #
  # Node
  #
  NODE_OPTIONS: '--max-old-space-size=4096'
  #
  # NVM
  #
  NVM_NODE_VERSION: v16
  #
  # Repo
  #
  MASTER_GIT_HOST: github.com
  MASTER_REPO_ORG: newrade
  MASTER_REPO_NAME: newrade-core
  PROJECT_GIT_HOST: github.com
  PROJECT_REPO_ORG: newrade
  PROJECT_REPO_NAME: newrade-core
  #
  # App
  #
  APP_DOMAIN: zedesignsystem.com
  APP_SUBDOMAIN: ''

jobs:

  build-test-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          clean: false

      - name: 'Checkout, Setup NodeJS + yarn and install dependencies'
        uses: ./.github/actions/base-node-setup

      - name: Verify dependencies
        run: yarn lerna:depcheck --scope @newrade/ze-*

      - name: Typecheck
        run: yarn lerna:typecheck --scope @newrade/ze-*

      - name: Lint (ls-lint) source files (core-docs)
        run: yarn ls-lint

      - name: Lint (ls-lint) source files
        run: yarn lerna:ls-lint --scope @newrade/ze-*

      - name: Lint source files
        run: yarn eslint ./packages/ze-*/src/ --ext ts,tsx

      - name: Build ze-design-system
        run: yarn lerna:build --scope @newrade/ze-design-system

      - name: Run unit tests
        run: yarn lerna:test --scope @newrade/ze-*

      - name: Build
        run: yarn lerna:build --scope @newrade/ze-design-website

      - name: Deploy
        if: ${{ env.APP_CI_DEPLOY }}
        uses: amondnet/vercel-action@v20
        with:
          github-comment: false
          scope: newrade
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: 'public'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: prj_Iu3M9OUBoUrzzQbljsaq6Z3WiRXJ
          working-directory: ./packages/ze-design-website
          alias-domains: |
            ${{ env.APP_HOST }}


